/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import domain.Korisnik;
import domain.Predmet;
import domain.Zvanje;
import domain.Profesor;
import java.util.List;
import controller.Controller;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Anđela
 */
public class MainForma extends javax.swing.JFrame {
    private Korisnik ulogovani;
    private List<Predmet> listaPredmeta;
    private List<Profesor> listaProfesora;
    private Controller controller;
    /**
     * Creates new form MainForma
     */
    public MainForma(Korisnik ulogovani) {
        initComponents();
        this.ulogovani = ulogovani;
        jLabelUlogovani.setText(ulogovani.toString());
        controller = Controller.getController();
        try {
            listaPredmeta = controller.getListaPredmeta();
            listaProfesora = controller.getListaProfesora();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Neuspesno ucitavanje iz baze " + ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
        popuniCmb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUlogovani = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPrezime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxZvanje = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonSacuvaj = new javax.swing.JButton();
        jButtonPrikazPredmeta = new javax.swing.JButton();
        jButtonIzmenaAngazovanja = new javax.swing.JButton();
        jComboBoxProfesor = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unos profesora");

        jLabel2.setText("Ime");

        jLabel3.setText("Prezime");

        jLabel4.setText("Zvanje");

        jLabel5.setText("Email");

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        jButtonPrikazPredmeta.setText("Prikazi sve predmete profesora");
        jButtonPrikazPredmeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikazPredmetaActionPerformed(evt);
            }
        });

        jButtonIzmenaAngazovanja.setText("Izmeni angazovanja profesora");
        jButtonIzmenaAngazovanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmenaAngazovanjaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(jComboBoxZvanje, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jButtonSacuvaj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelUlogovani, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonIzmenaAngazovanja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonPrikazPredmeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))))))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelUlogovani)
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxZvanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSacuvaj)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrikazPredmeta)
                    .addComponent(jComboBoxProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonIzmenaAngazovanja)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        // TODO add your handling code here:
        String errorMessage = "";
        if(jTextFieldIme.getText() == null || jTextFieldIme.getText().isEmpty()){
            errorMessage += "Niste uneli ime profesora \n";
        }
        if(jTextFieldPrezime.getText() == null || jTextFieldIme.getText().isEmpty()){
            errorMessage += "Niste uneli prezime profesora \n";
        }
        if(jComboBoxZvanje.getSelectedItem() == null){
            errorMessage += "Niste izabrali zvanje profesora \n";
        }
        if(jTextFieldEmail.getText() == null){
            errorMessage += "Niste uneli email profesora \n";
        }
        
        if(!errorMessage.isEmpty()){
            JOptionPane.showMessageDialog(this, errorMessage, "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            Profesor p = new Profesor(null, jTextFieldIme.getText(), jTextFieldPrezime.getText(), jTextFieldEmail.getText(), (Zvanje)jComboBoxZvanje.getSelectedItem());
            if(listaProfesora.contains(p)){
                JOptionPane.showMessageDialog(this, "Profesor vec postoji u bazi", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                controller.dodajProfesora(p);
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Neuspesno unet profesor u bazu " + ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(this, "Uspesno unet profesor u bazu", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jButtonPrikazPredmetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikazPredmetaActionPerformed
        // TODO add your handling code here:
        Profesor p = (Profesor) jComboBoxProfesor.getSelectedItem();
        new PrikazBrisanjeDodavanjeAngazovanja(this, true, p,0).setVisible(true);
    }//GEN-LAST:event_jButtonPrikazPredmetaActionPerformed

    private void jButtonIzmenaAngazovanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmenaAngazovanjaActionPerformed
        // TODO add your handling code here:
        Profesor p = (Profesor) jComboBoxProfesor.getSelectedItem();
        new PrikazBrisanjeDodavanjeAngazovanja(this, true, p,1).setVisible(true);
    }//GEN-LAST:event_jButtonIzmenaAngazovanjaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzmenaAngazovanja;
    private javax.swing.JButton jButtonPrikazPredmeta;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JComboBox jComboBoxProfesor;
    private javax.swing.JComboBox jComboBoxZvanje;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelUlogovani;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    // End of variables declaration//GEN-END:variables

    private void popuniCmb() {
        for(Zvanje z : Zvanje.values()){
            jComboBoxZvanje.addItem(z);
        }
        for(Profesor p : listaProfesora){
            jComboBoxProfesor.addItem(p);
        }
    }
}
